// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GenData.proto

#ifndef PROTOBUF_GenData_2eproto__INCLUDED
#define PROTOBUF_GenData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GenData_2eproto();
void protobuf_AssignDesc_GenData_2eproto();
void protobuf_ShutdownFile_GenData_2eproto();

class CaffeGenData;
class CaffeGenData_DataField;
class CaffeGenData_FieldTranslate;

enum CaffeGenData_IterateType {
  CaffeGenData_IterateType_ITERATE_WORD = 1,
  CaffeGenData_IterateType_ITERATE_REC = 2
};
bool CaffeGenData_IterateType_IsValid(int value);
const CaffeGenData_IterateType CaffeGenData_IterateType_IterateType_MIN = CaffeGenData_IterateType_ITERATE_WORD;
const CaffeGenData_IterateType CaffeGenData_IterateType_IterateType_MAX = CaffeGenData_IterateType_ITERATE_REC;
const int CaffeGenData_IterateType_IterateType_ARRAYSIZE = CaffeGenData_IterateType_IterateType_MAX + 1;

const ::google::protobuf::EnumDescriptor* CaffeGenData_IterateType_descriptor();
inline const ::std::string& CaffeGenData_IterateType_Name(CaffeGenData_IterateType value) {
  return ::google::protobuf::internal::NameOfEnum(
    CaffeGenData_IterateType_descriptor(), value);
}
inline bool CaffeGenData_IterateType_Parse(
    const ::std::string& name, CaffeGenData_IterateType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CaffeGenData_IterateType>(
    CaffeGenData_IterateType_descriptor(), name, value);
}
enum CaffeGenData_DataSrc {
  CaffeGenData_DataSrc_DATA_SRC_BOOKS = 1
};
bool CaffeGenData_DataSrc_IsValid(int value);
const CaffeGenData_DataSrc CaffeGenData_DataSrc_DataSrc_MIN = CaffeGenData_DataSrc_DATA_SRC_BOOKS;
const CaffeGenData_DataSrc CaffeGenData_DataSrc_DataSrc_MAX = CaffeGenData_DataSrc_DATA_SRC_BOOKS;
const int CaffeGenData_DataSrc_DataSrc_ARRAYSIZE = CaffeGenData_DataSrc_DataSrc_MAX + 1;

const ::google::protobuf::EnumDescriptor* CaffeGenData_DataSrc_descriptor();
inline const ::std::string& CaffeGenData_DataSrc_Name(CaffeGenData_DataSrc value) {
  return ::google::protobuf::internal::NameOfEnum(
    CaffeGenData_DataSrc_descriptor(), value);
}
inline bool CaffeGenData_DataSrc_Parse(
    const ::std::string& name, CaffeGenData_DataSrc* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CaffeGenData_DataSrc>(
    CaffeGenData_DataSrc_descriptor(), name, value);
}
enum CaffeGenData_NetEndType {
  CaffeGenData_NetEndType_END_VALID = 1,
  CaffeGenData_NetEndType_END_ONE_HOT = 2,
  CaffeGenData_NetEndType_END_MULTI_HOT = 3
};
bool CaffeGenData_NetEndType_IsValid(int value);
const CaffeGenData_NetEndType CaffeGenData_NetEndType_NetEndType_MIN = CaffeGenData_NetEndType_END_VALID;
const CaffeGenData_NetEndType CaffeGenData_NetEndType_NetEndType_MAX = CaffeGenData_NetEndType_END_MULTI_HOT;
const int CaffeGenData_NetEndType_NetEndType_ARRAYSIZE = CaffeGenData_NetEndType_NetEndType_MAX + 1;

const ::google::protobuf::EnumDescriptor* CaffeGenData_NetEndType_descriptor();
inline const ::std::string& CaffeGenData_NetEndType_Name(CaffeGenData_NetEndType value) {
  return ::google::protobuf::internal::NameOfEnum(
    CaffeGenData_NetEndType_descriptor(), value);
}
inline bool CaffeGenData_NetEndType_Parse(
    const ::std::string& name, CaffeGenData_NetEndType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CaffeGenData_NetEndType>(
    CaffeGenData_NetEndType_descriptor(), name, value);
}
// ===================================================================

class CaffeGenData_DataField : public ::google::protobuf::Message {
 public:
  CaffeGenData_DataField();
  virtual ~CaffeGenData_DataField();

  CaffeGenData_DataField(const CaffeGenData_DataField& from);

  inline CaffeGenData_DataField& operator=(const CaffeGenData_DataField& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CaffeGenData_DataField& default_instance();

  void Swap(CaffeGenData_DataField* other);

  // implements Message ----------------------------------------------

  CaffeGenData_DataField* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CaffeGenData_DataField& from);
  void MergeFrom(const CaffeGenData_DataField& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string var_name = 1;
  inline bool has_var_name() const;
  inline void clear_var_name();
  static const int kVarNameFieldNumber = 1;
  inline const ::std::string& var_name() const;
  inline void set_var_name(const ::std::string& value);
  inline void set_var_name(const char* value);
  inline void set_var_name(const char* value, size_t size);
  inline ::std::string* mutable_var_name();
  inline ::std::string* release_var_name();
  inline void set_allocated_var_name(::std::string* var_name);

  // required string field_name = 2;
  inline bool has_field_name() const;
  inline void clear_field_name();
  static const int kFieldNameFieldNumber = 2;
  inline const ::std::string& field_name() const;
  inline void set_field_name(const ::std::string& value);
  inline void set_field_name(const char* value);
  inline void set_field_name(const char* value, size_t size);
  inline ::std::string* mutable_field_name();
  inline ::std::string* release_field_name();
  inline void set_allocated_field_name(::std::string* field_name);

  // @@protoc_insertion_point(class_scope:CaffeGenData.DataField)
 private:
  inline void set_has_var_name();
  inline void clear_has_var_name();
  inline void set_has_field_name();
  inline void clear_has_field_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* var_name_;
  ::std::string* field_name_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_GenData_2eproto();
  friend void protobuf_AssignDesc_GenData_2eproto();
  friend void protobuf_ShutdownFile_GenData_2eproto();

  void InitAsDefaultInstance();
  static CaffeGenData_DataField* default_instance_;
};
// -------------------------------------------------------------------

class CaffeGenData_FieldTranslate : public ::google::protobuf::Message {
 public:
  CaffeGenData_FieldTranslate();
  virtual ~CaffeGenData_FieldTranslate();

  CaffeGenData_FieldTranslate(const CaffeGenData_FieldTranslate& from);

  inline CaffeGenData_FieldTranslate& operator=(const CaffeGenData_FieldTranslate& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CaffeGenData_FieldTranslate& default_instance();

  void Swap(CaffeGenData_FieldTranslate* other);

  // implements Message ----------------------------------------------

  CaffeGenData_FieldTranslate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CaffeGenData_FieldTranslate& from);
  void MergeFrom(const CaffeGenData_FieldTranslate& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string var_name = 1;
  inline bool has_var_name() const;
  inline void clear_var_name();
  static const int kVarNameFieldNumber = 1;
  inline const ::std::string& var_name() const;
  inline void set_var_name(const ::std::string& value);
  inline void set_var_name(const char* value);
  inline void set_var_name(const char* value, size_t size);
  inline ::std::string* mutable_var_name();
  inline ::std::string* release_var_name();
  inline void set_allocated_var_name(::std::string* var_name);

  // required string table_name = 2;
  inline bool has_table_name() const;
  inline void clear_table_name();
  static const int kTableNameFieldNumber = 2;
  inline const ::std::string& table_name() const;
  inline void set_table_name(const ::std::string& value);
  inline void set_table_name(const char* value);
  inline void set_table_name(const char* value, size_t size);
  inline ::std::string* mutable_table_name();
  inline ::std::string* release_table_name();
  inline void set_allocated_table_name(::std::string* table_name);

  // optional bool b_can_replace = 3;
  inline bool has_b_can_replace() const;
  inline void clear_b_can_replace();
  static const int kBCanReplaceFieldNumber = 3;
  inline bool b_can_replace() const;
  inline void set_b_can_replace(bool value);

  // optional int32 max_instances = 4;
  inline bool has_max_instances() const;
  inline void clear_max_instances();
  static const int kMaxInstancesFieldNumber = 4;
  inline ::google::protobuf::int32 max_instances() const;
  inline void set_max_instances(::google::protobuf::int32 value);

  // optional float replace_prob = 5;
  inline bool has_replace_prob() const;
  inline void clear_replace_prob();
  static const int kReplaceProbFieldNumber = 5;
  inline float replace_prob() const;
  inline void set_replace_prob(float value);

  // @@protoc_insertion_point(class_scope:CaffeGenData.FieldTranslate)
 private:
  inline void set_has_var_name();
  inline void clear_has_var_name();
  inline void set_has_table_name();
  inline void clear_has_table_name();
  inline void set_has_b_can_replace();
  inline void clear_has_b_can_replace();
  inline void set_has_max_instances();
  inline void clear_has_max_instances();
  inline void set_has_replace_prob();
  inline void clear_has_replace_prob();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* var_name_;
  ::std::string* table_name_;
  bool b_can_replace_;
  ::google::protobuf::int32 max_instances_;
  float replace_prob_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_GenData_2eproto();
  friend void protobuf_AssignDesc_GenData_2eproto();
  friend void protobuf_ShutdownFile_GenData_2eproto();

  void InitAsDefaultInstance();
  static CaffeGenData_FieldTranslate* default_instance_;
};
// -------------------------------------------------------------------

class CaffeGenData : public ::google::protobuf::Message {
 public:
  CaffeGenData();
  virtual ~CaffeGenData();

  CaffeGenData(const CaffeGenData& from);

  inline CaffeGenData& operator=(const CaffeGenData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CaffeGenData& default_instance();

  void Swap(CaffeGenData* other);

  // implements Message ----------------------------------------------

  CaffeGenData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CaffeGenData& from);
  void MergeFrom(const CaffeGenData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef CaffeGenData_DataField DataField;
  typedef CaffeGenData_FieldTranslate FieldTranslate;

  typedef CaffeGenData_IterateType IterateType;
  static const IterateType ITERATE_WORD = CaffeGenData_IterateType_ITERATE_WORD;
  static const IterateType ITERATE_REC = CaffeGenData_IterateType_ITERATE_REC;
  static inline bool IterateType_IsValid(int value) {
    return CaffeGenData_IterateType_IsValid(value);
  }
  static const IterateType IterateType_MIN =
    CaffeGenData_IterateType_IterateType_MIN;
  static const IterateType IterateType_MAX =
    CaffeGenData_IterateType_IterateType_MAX;
  static const int IterateType_ARRAYSIZE =
    CaffeGenData_IterateType_IterateType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  IterateType_descriptor() {
    return CaffeGenData_IterateType_descriptor();
  }
  static inline const ::std::string& IterateType_Name(IterateType value) {
    return CaffeGenData_IterateType_Name(value);
  }
  static inline bool IterateType_Parse(const ::std::string& name,
      IterateType* value) {
    return CaffeGenData_IterateType_Parse(name, value);
  }

  typedef CaffeGenData_DataSrc DataSrc;
  static const DataSrc DATA_SRC_BOOKS = CaffeGenData_DataSrc_DATA_SRC_BOOKS;
  static inline bool DataSrc_IsValid(int value) {
    return CaffeGenData_DataSrc_IsValid(value);
  }
  static const DataSrc DataSrc_MIN =
    CaffeGenData_DataSrc_DataSrc_MIN;
  static const DataSrc DataSrc_MAX =
    CaffeGenData_DataSrc_DataSrc_MAX;
  static const int DataSrc_ARRAYSIZE =
    CaffeGenData_DataSrc_DataSrc_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  DataSrc_descriptor() {
    return CaffeGenData_DataSrc_descriptor();
  }
  static inline const ::std::string& DataSrc_Name(DataSrc value) {
    return CaffeGenData_DataSrc_Name(value);
  }
  static inline bool DataSrc_Parse(const ::std::string& name,
      DataSrc* value) {
    return CaffeGenData_DataSrc_Parse(name, value);
  }

  typedef CaffeGenData_NetEndType NetEndType;
  static const NetEndType END_VALID = CaffeGenData_NetEndType_END_VALID;
  static const NetEndType END_ONE_HOT = CaffeGenData_NetEndType_END_ONE_HOT;
  static const NetEndType END_MULTI_HOT = CaffeGenData_NetEndType_END_MULTI_HOT;
  static inline bool NetEndType_IsValid(int value) {
    return CaffeGenData_NetEndType_IsValid(value);
  }
  static const NetEndType NetEndType_MIN =
    CaffeGenData_NetEndType_NetEndType_MIN;
  static const NetEndType NetEndType_MAX =
    CaffeGenData_NetEndType_NetEndType_MAX;
  static const int NetEndType_ARRAYSIZE =
    CaffeGenData_NetEndType_NetEndType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  NetEndType_descriptor() {
    return CaffeGenData_NetEndType_descriptor();
  }
  static inline const ::std::string& NetEndType_Name(NetEndType value) {
    return CaffeGenData_NetEndType_Name(value);
  }
  static inline bool NetEndType_Parse(const ::std::string& name,
      NetEndType* value) {
    return CaffeGenData_NetEndType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .CaffeGenData.IterateType iterate_type = 2;
  inline bool has_iterate_type() const;
  inline void clear_iterate_type();
  static const int kIterateTypeFieldNumber = 2;
  inline ::CaffeGenData_IterateType iterate_type() const;
  inline void set_iterate_type(::CaffeGenData_IterateType value);

  // required .CaffeGenData.DataSrc data_src = 3;
  inline bool has_data_src() const;
  inline void clear_data_src();
  static const int kDataSrcFieldNumber = 3;
  inline ::CaffeGenData_DataSrc data_src() const;
  inline void set_data_src(::CaffeGenData_DataSrc value);

  // repeated .CaffeGenData.DataField data_fields = 4;
  inline int data_fields_size() const;
  inline void clear_data_fields();
  static const int kDataFieldsFieldNumber = 4;
  inline const ::CaffeGenData_DataField& data_fields(int index) const;
  inline ::CaffeGenData_DataField* mutable_data_fields(int index);
  inline ::CaffeGenData_DataField* add_data_fields();
  inline const ::google::protobuf::RepeatedPtrField< ::CaffeGenData_DataField >&
      data_fields() const;
  inline ::google::protobuf::RepeatedPtrField< ::CaffeGenData_DataField >*
      mutable_data_fields();

  // repeated .CaffeGenData.FieldTranslate input_field_translates = 5;
  inline int input_field_translates_size() const;
  inline void clear_input_field_translates();
  static const int kInputFieldTranslatesFieldNumber = 5;
  inline const ::CaffeGenData_FieldTranslate& input_field_translates(int index) const;
  inline ::CaffeGenData_FieldTranslate* mutable_input_field_translates(int index);
  inline ::CaffeGenData_FieldTranslate* add_input_field_translates();
  inline const ::google::protobuf::RepeatedPtrField< ::CaffeGenData_FieldTranslate >&
      input_field_translates() const;
  inline ::google::protobuf::RepeatedPtrField< ::CaffeGenData_FieldTranslate >*
      mutable_input_field_translates();

  // repeated .CaffeGenData.FieldTranslate output_field_translates = 6;
  inline int output_field_translates_size() const;
  inline void clear_output_field_translates();
  static const int kOutputFieldTranslatesFieldNumber = 6;
  inline const ::CaffeGenData_FieldTranslate& output_field_translates(int index) const;
  inline ::CaffeGenData_FieldTranslate* mutable_output_field_translates(int index);
  inline ::CaffeGenData_FieldTranslate* add_output_field_translates();
  inline const ::google::protobuf::RepeatedPtrField< ::CaffeGenData_FieldTranslate >&
      output_field_translates() const;
  inline ::google::protobuf::RepeatedPtrField< ::CaffeGenData_FieldTranslate >*
      mutable_output_field_translates();

  // required string files_core_dir = 7;
  inline bool has_files_core_dir() const;
  inline void clear_files_core_dir();
  static const int kFilesCoreDirFieldNumber = 7;
  inline const ::std::string& files_core_dir() const;
  inline void set_files_core_dir(const ::std::string& value);
  inline void set_files_core_dir(const char* value);
  inline void set_files_core_dir(const char* value, size_t size);
  inline ::std::string* mutable_files_core_dir();
  inline ::std::string* release_files_core_dir();
  inline void set_allocated_files_core_dir(::std::string* files_core_dir);

  // required string test_list_file_name = 8;
  inline bool has_test_list_file_name() const;
  inline void clear_test_list_file_name();
  static const int kTestListFileNameFieldNumber = 8;
  inline const ::std::string& test_list_file_name() const;
  inline void set_test_list_file_name(const ::std::string& value);
  inline void set_test_list_file_name(const char* value);
  inline void set_test_list_file_name(const char* value, size_t size);
  inline ::std::string* mutable_test_list_file_name();
  inline ::std::string* release_test_list_file_name();
  inline void set_allocated_test_list_file_name(::std::string* test_list_file_name);

  // required string train_list_file_name = 9;
  inline bool has_train_list_file_name() const;
  inline void clear_train_list_file_name();
  static const int kTrainListFileNameFieldNumber = 9;
  inline const ::std::string& train_list_file_name() const;
  inline void set_train_list_file_name(const ::std::string& value);
  inline void set_train_list_file_name(const char* value);
  inline void set_train_list_file_name(const char* value, size_t size);
  inline ::std::string* mutable_train_list_file_name();
  inline ::std::string* release_train_list_file_name();
  inline void set_allocated_train_list_file_name(::std::string* train_list_file_name);

  // required .CaffeGenData.NetEndType net_end_type = 10;
  inline bool has_net_end_type() const;
  inline void clear_net_end_type();
  static const int kNetEndTypeFieldNumber = 10;
  inline ::CaffeGenData_NetEndType net_end_type() const;
  inline void set_net_end_type(::CaffeGenData_NetEndType value);

  // required string proto_file_name = 11;
  inline bool has_proto_file_name() const;
  inline void clear_proto_file_name();
  static const int kProtoFileNameFieldNumber = 11;
  inline const ::std::string& proto_file_name() const;
  inline void set_proto_file_name(const ::std::string& value);
  inline void set_proto_file_name(const char* value);
  inline void set_proto_file_name(const char* value, size_t size);
  inline ::std::string* mutable_proto_file_name();
  inline ::std::string* release_proto_file_name();
  inline void set_allocated_proto_file_name(::std::string* proto_file_name);

  // required string model_file_name = 12;
  inline bool has_model_file_name() const;
  inline void clear_model_file_name();
  static const int kModelFileNameFieldNumber = 12;
  inline const ::std::string& model_file_name() const;
  inline void set_model_file_name(const ::std::string& value);
  inline void set_model_file_name(const char* value);
  inline void set_model_file_name(const char* value, size_t size);
  inline ::std::string* mutable_model_file_name();
  inline ::std::string* release_model_file_name();
  inline void set_allocated_model_file_name(::std::string* model_file_name);

  // required string config_file_name = 13;
  inline bool has_config_file_name() const;
  inline void clear_config_file_name();
  static const int kConfigFileNameFieldNumber = 13;
  inline const ::std::string& config_file_name() const;
  inline void set_config_file_name(const ::std::string& value);
  inline void set_config_file_name(const char* value);
  inline void set_config_file_name(const char* value, size_t size);
  inline ::std::string* mutable_config_file_name();
  inline ::std::string* release_config_file_name();
  inline void set_allocated_config_file_name(::std::string* config_file_name);

  // @@protoc_insertion_point(class_scope:CaffeGenData)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_iterate_type();
  inline void clear_has_iterate_type();
  inline void set_has_data_src();
  inline void clear_has_data_src();
  inline void set_has_files_core_dir();
  inline void clear_has_files_core_dir();
  inline void set_has_test_list_file_name();
  inline void clear_has_test_list_file_name();
  inline void set_has_train_list_file_name();
  inline void clear_has_train_list_file_name();
  inline void set_has_net_end_type();
  inline void clear_has_net_end_type();
  inline void set_has_proto_file_name();
  inline void clear_has_proto_file_name();
  inline void set_has_model_file_name();
  inline void clear_has_model_file_name();
  inline void set_has_config_file_name();
  inline void clear_has_config_file_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  int iterate_type_;
  int data_src_;
  ::google::protobuf::RepeatedPtrField< ::CaffeGenData_DataField > data_fields_;
  ::google::protobuf::RepeatedPtrField< ::CaffeGenData_FieldTranslate > input_field_translates_;
  ::google::protobuf::RepeatedPtrField< ::CaffeGenData_FieldTranslate > output_field_translates_;
  ::std::string* files_core_dir_;
  ::std::string* test_list_file_name_;
  ::std::string* train_list_file_name_;
  ::std::string* proto_file_name_;
  ::std::string* model_file_name_;
  ::std::string* config_file_name_;
  int net_end_type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(13 + 31) / 32];

  friend void  protobuf_AddDesc_GenData_2eproto();
  friend void protobuf_AssignDesc_GenData_2eproto();
  friend void protobuf_ShutdownFile_GenData_2eproto();

  void InitAsDefaultInstance();
  static CaffeGenData* default_instance_;
};
// ===================================================================


// ===================================================================

// CaffeGenData_DataField

// required string var_name = 1;
inline bool CaffeGenData_DataField::has_var_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CaffeGenData_DataField::set_has_var_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CaffeGenData_DataField::clear_has_var_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CaffeGenData_DataField::clear_var_name() {
  if (var_name_ != &::google::protobuf::internal::kEmptyString) {
    var_name_->clear();
  }
  clear_has_var_name();
}
inline const ::std::string& CaffeGenData_DataField::var_name() const {
  return *var_name_;
}
inline void CaffeGenData_DataField::set_var_name(const ::std::string& value) {
  set_has_var_name();
  if (var_name_ == &::google::protobuf::internal::kEmptyString) {
    var_name_ = new ::std::string;
  }
  var_name_->assign(value);
}
inline void CaffeGenData_DataField::set_var_name(const char* value) {
  set_has_var_name();
  if (var_name_ == &::google::protobuf::internal::kEmptyString) {
    var_name_ = new ::std::string;
  }
  var_name_->assign(value);
}
inline void CaffeGenData_DataField::set_var_name(const char* value, size_t size) {
  set_has_var_name();
  if (var_name_ == &::google::protobuf::internal::kEmptyString) {
    var_name_ = new ::std::string;
  }
  var_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CaffeGenData_DataField::mutable_var_name() {
  set_has_var_name();
  if (var_name_ == &::google::protobuf::internal::kEmptyString) {
    var_name_ = new ::std::string;
  }
  return var_name_;
}
inline ::std::string* CaffeGenData_DataField::release_var_name() {
  clear_has_var_name();
  if (var_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = var_name_;
    var_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CaffeGenData_DataField::set_allocated_var_name(::std::string* var_name) {
  if (var_name_ != &::google::protobuf::internal::kEmptyString) {
    delete var_name_;
  }
  if (var_name) {
    set_has_var_name();
    var_name_ = var_name;
  } else {
    clear_has_var_name();
    var_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string field_name = 2;
inline bool CaffeGenData_DataField::has_field_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CaffeGenData_DataField::set_has_field_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CaffeGenData_DataField::clear_has_field_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CaffeGenData_DataField::clear_field_name() {
  if (field_name_ != &::google::protobuf::internal::kEmptyString) {
    field_name_->clear();
  }
  clear_has_field_name();
}
inline const ::std::string& CaffeGenData_DataField::field_name() const {
  return *field_name_;
}
inline void CaffeGenData_DataField::set_field_name(const ::std::string& value) {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  field_name_->assign(value);
}
inline void CaffeGenData_DataField::set_field_name(const char* value) {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  field_name_->assign(value);
}
inline void CaffeGenData_DataField::set_field_name(const char* value, size_t size) {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  field_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CaffeGenData_DataField::mutable_field_name() {
  set_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    field_name_ = new ::std::string;
  }
  return field_name_;
}
inline ::std::string* CaffeGenData_DataField::release_field_name() {
  clear_has_field_name();
  if (field_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = field_name_;
    field_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CaffeGenData_DataField::set_allocated_field_name(::std::string* field_name) {
  if (field_name_ != &::google::protobuf::internal::kEmptyString) {
    delete field_name_;
  }
  if (field_name) {
    set_has_field_name();
    field_name_ = field_name;
  } else {
    clear_has_field_name();
    field_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// CaffeGenData_FieldTranslate

// optional string var_name = 1;
inline bool CaffeGenData_FieldTranslate::has_var_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CaffeGenData_FieldTranslate::set_has_var_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CaffeGenData_FieldTranslate::clear_has_var_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CaffeGenData_FieldTranslate::clear_var_name() {
  if (var_name_ != &::google::protobuf::internal::kEmptyString) {
    var_name_->clear();
  }
  clear_has_var_name();
}
inline const ::std::string& CaffeGenData_FieldTranslate::var_name() const {
  return *var_name_;
}
inline void CaffeGenData_FieldTranslate::set_var_name(const ::std::string& value) {
  set_has_var_name();
  if (var_name_ == &::google::protobuf::internal::kEmptyString) {
    var_name_ = new ::std::string;
  }
  var_name_->assign(value);
}
inline void CaffeGenData_FieldTranslate::set_var_name(const char* value) {
  set_has_var_name();
  if (var_name_ == &::google::protobuf::internal::kEmptyString) {
    var_name_ = new ::std::string;
  }
  var_name_->assign(value);
}
inline void CaffeGenData_FieldTranslate::set_var_name(const char* value, size_t size) {
  set_has_var_name();
  if (var_name_ == &::google::protobuf::internal::kEmptyString) {
    var_name_ = new ::std::string;
  }
  var_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CaffeGenData_FieldTranslate::mutable_var_name() {
  set_has_var_name();
  if (var_name_ == &::google::protobuf::internal::kEmptyString) {
    var_name_ = new ::std::string;
  }
  return var_name_;
}
inline ::std::string* CaffeGenData_FieldTranslate::release_var_name() {
  clear_has_var_name();
  if (var_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = var_name_;
    var_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CaffeGenData_FieldTranslate::set_allocated_var_name(::std::string* var_name) {
  if (var_name_ != &::google::protobuf::internal::kEmptyString) {
    delete var_name_;
  }
  if (var_name) {
    set_has_var_name();
    var_name_ = var_name;
  } else {
    clear_has_var_name();
    var_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string table_name = 2;
inline bool CaffeGenData_FieldTranslate::has_table_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CaffeGenData_FieldTranslate::set_has_table_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CaffeGenData_FieldTranslate::clear_has_table_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CaffeGenData_FieldTranslate::clear_table_name() {
  if (table_name_ != &::google::protobuf::internal::kEmptyString) {
    table_name_->clear();
  }
  clear_has_table_name();
}
inline const ::std::string& CaffeGenData_FieldTranslate::table_name() const {
  return *table_name_;
}
inline void CaffeGenData_FieldTranslate::set_table_name(const ::std::string& value) {
  set_has_table_name();
  if (table_name_ == &::google::protobuf::internal::kEmptyString) {
    table_name_ = new ::std::string;
  }
  table_name_->assign(value);
}
inline void CaffeGenData_FieldTranslate::set_table_name(const char* value) {
  set_has_table_name();
  if (table_name_ == &::google::protobuf::internal::kEmptyString) {
    table_name_ = new ::std::string;
  }
  table_name_->assign(value);
}
inline void CaffeGenData_FieldTranslate::set_table_name(const char* value, size_t size) {
  set_has_table_name();
  if (table_name_ == &::google::protobuf::internal::kEmptyString) {
    table_name_ = new ::std::string;
  }
  table_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CaffeGenData_FieldTranslate::mutable_table_name() {
  set_has_table_name();
  if (table_name_ == &::google::protobuf::internal::kEmptyString) {
    table_name_ = new ::std::string;
  }
  return table_name_;
}
inline ::std::string* CaffeGenData_FieldTranslate::release_table_name() {
  clear_has_table_name();
  if (table_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = table_name_;
    table_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CaffeGenData_FieldTranslate::set_allocated_table_name(::std::string* table_name) {
  if (table_name_ != &::google::protobuf::internal::kEmptyString) {
    delete table_name_;
  }
  if (table_name) {
    set_has_table_name();
    table_name_ = table_name;
  } else {
    clear_has_table_name();
    table_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bool b_can_replace = 3;
inline bool CaffeGenData_FieldTranslate::has_b_can_replace() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CaffeGenData_FieldTranslate::set_has_b_can_replace() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CaffeGenData_FieldTranslate::clear_has_b_can_replace() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CaffeGenData_FieldTranslate::clear_b_can_replace() {
  b_can_replace_ = false;
  clear_has_b_can_replace();
}
inline bool CaffeGenData_FieldTranslate::b_can_replace() const {
  return b_can_replace_;
}
inline void CaffeGenData_FieldTranslate::set_b_can_replace(bool value) {
  set_has_b_can_replace();
  b_can_replace_ = value;
}

// optional int32 max_instances = 4;
inline bool CaffeGenData_FieldTranslate::has_max_instances() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CaffeGenData_FieldTranslate::set_has_max_instances() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CaffeGenData_FieldTranslate::clear_has_max_instances() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CaffeGenData_FieldTranslate::clear_max_instances() {
  max_instances_ = 0;
  clear_has_max_instances();
}
inline ::google::protobuf::int32 CaffeGenData_FieldTranslate::max_instances() const {
  return max_instances_;
}
inline void CaffeGenData_FieldTranslate::set_max_instances(::google::protobuf::int32 value) {
  set_has_max_instances();
  max_instances_ = value;
}

// optional float replace_prob = 5;
inline bool CaffeGenData_FieldTranslate::has_replace_prob() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CaffeGenData_FieldTranslate::set_has_replace_prob() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CaffeGenData_FieldTranslate::clear_has_replace_prob() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CaffeGenData_FieldTranslate::clear_replace_prob() {
  replace_prob_ = 0;
  clear_has_replace_prob();
}
inline float CaffeGenData_FieldTranslate::replace_prob() const {
  return replace_prob_;
}
inline void CaffeGenData_FieldTranslate::set_replace_prob(float value) {
  set_has_replace_prob();
  replace_prob_ = value;
}

// -------------------------------------------------------------------

// CaffeGenData

// required string name = 1;
inline bool CaffeGenData::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CaffeGenData::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CaffeGenData::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CaffeGenData::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& CaffeGenData::name() const {
  return *name_;
}
inline void CaffeGenData::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void CaffeGenData::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void CaffeGenData::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CaffeGenData::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* CaffeGenData::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CaffeGenData::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required .CaffeGenData.IterateType iterate_type = 2;
inline bool CaffeGenData::has_iterate_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CaffeGenData::set_has_iterate_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CaffeGenData::clear_has_iterate_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CaffeGenData::clear_iterate_type() {
  iterate_type_ = 1;
  clear_has_iterate_type();
}
inline ::CaffeGenData_IterateType CaffeGenData::iterate_type() const {
  return static_cast< ::CaffeGenData_IterateType >(iterate_type_);
}
inline void CaffeGenData::set_iterate_type(::CaffeGenData_IterateType value) {
  assert(::CaffeGenData_IterateType_IsValid(value));
  set_has_iterate_type();
  iterate_type_ = value;
}

// required .CaffeGenData.DataSrc data_src = 3;
inline bool CaffeGenData::has_data_src() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CaffeGenData::set_has_data_src() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CaffeGenData::clear_has_data_src() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CaffeGenData::clear_data_src() {
  data_src_ = 1;
  clear_has_data_src();
}
inline ::CaffeGenData_DataSrc CaffeGenData::data_src() const {
  return static_cast< ::CaffeGenData_DataSrc >(data_src_);
}
inline void CaffeGenData::set_data_src(::CaffeGenData_DataSrc value) {
  assert(::CaffeGenData_DataSrc_IsValid(value));
  set_has_data_src();
  data_src_ = value;
}

// repeated .CaffeGenData.DataField data_fields = 4;
inline int CaffeGenData::data_fields_size() const {
  return data_fields_.size();
}
inline void CaffeGenData::clear_data_fields() {
  data_fields_.Clear();
}
inline const ::CaffeGenData_DataField& CaffeGenData::data_fields(int index) const {
  return data_fields_.Get(index);
}
inline ::CaffeGenData_DataField* CaffeGenData::mutable_data_fields(int index) {
  return data_fields_.Mutable(index);
}
inline ::CaffeGenData_DataField* CaffeGenData::add_data_fields() {
  return data_fields_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CaffeGenData_DataField >&
CaffeGenData::data_fields() const {
  return data_fields_;
}
inline ::google::protobuf::RepeatedPtrField< ::CaffeGenData_DataField >*
CaffeGenData::mutable_data_fields() {
  return &data_fields_;
}

// repeated .CaffeGenData.FieldTranslate input_field_translates = 5;
inline int CaffeGenData::input_field_translates_size() const {
  return input_field_translates_.size();
}
inline void CaffeGenData::clear_input_field_translates() {
  input_field_translates_.Clear();
}
inline const ::CaffeGenData_FieldTranslate& CaffeGenData::input_field_translates(int index) const {
  return input_field_translates_.Get(index);
}
inline ::CaffeGenData_FieldTranslate* CaffeGenData::mutable_input_field_translates(int index) {
  return input_field_translates_.Mutable(index);
}
inline ::CaffeGenData_FieldTranslate* CaffeGenData::add_input_field_translates() {
  return input_field_translates_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CaffeGenData_FieldTranslate >&
CaffeGenData::input_field_translates() const {
  return input_field_translates_;
}
inline ::google::protobuf::RepeatedPtrField< ::CaffeGenData_FieldTranslate >*
CaffeGenData::mutable_input_field_translates() {
  return &input_field_translates_;
}

// repeated .CaffeGenData.FieldTranslate output_field_translates = 6;
inline int CaffeGenData::output_field_translates_size() const {
  return output_field_translates_.size();
}
inline void CaffeGenData::clear_output_field_translates() {
  output_field_translates_.Clear();
}
inline const ::CaffeGenData_FieldTranslate& CaffeGenData::output_field_translates(int index) const {
  return output_field_translates_.Get(index);
}
inline ::CaffeGenData_FieldTranslate* CaffeGenData::mutable_output_field_translates(int index) {
  return output_field_translates_.Mutable(index);
}
inline ::CaffeGenData_FieldTranslate* CaffeGenData::add_output_field_translates() {
  return output_field_translates_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CaffeGenData_FieldTranslate >&
CaffeGenData::output_field_translates() const {
  return output_field_translates_;
}
inline ::google::protobuf::RepeatedPtrField< ::CaffeGenData_FieldTranslate >*
CaffeGenData::mutable_output_field_translates() {
  return &output_field_translates_;
}

// required string files_core_dir = 7;
inline bool CaffeGenData::has_files_core_dir() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CaffeGenData::set_has_files_core_dir() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CaffeGenData::clear_has_files_core_dir() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CaffeGenData::clear_files_core_dir() {
  if (files_core_dir_ != &::google::protobuf::internal::kEmptyString) {
    files_core_dir_->clear();
  }
  clear_has_files_core_dir();
}
inline const ::std::string& CaffeGenData::files_core_dir() const {
  return *files_core_dir_;
}
inline void CaffeGenData::set_files_core_dir(const ::std::string& value) {
  set_has_files_core_dir();
  if (files_core_dir_ == &::google::protobuf::internal::kEmptyString) {
    files_core_dir_ = new ::std::string;
  }
  files_core_dir_->assign(value);
}
inline void CaffeGenData::set_files_core_dir(const char* value) {
  set_has_files_core_dir();
  if (files_core_dir_ == &::google::protobuf::internal::kEmptyString) {
    files_core_dir_ = new ::std::string;
  }
  files_core_dir_->assign(value);
}
inline void CaffeGenData::set_files_core_dir(const char* value, size_t size) {
  set_has_files_core_dir();
  if (files_core_dir_ == &::google::protobuf::internal::kEmptyString) {
    files_core_dir_ = new ::std::string;
  }
  files_core_dir_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CaffeGenData::mutable_files_core_dir() {
  set_has_files_core_dir();
  if (files_core_dir_ == &::google::protobuf::internal::kEmptyString) {
    files_core_dir_ = new ::std::string;
  }
  return files_core_dir_;
}
inline ::std::string* CaffeGenData::release_files_core_dir() {
  clear_has_files_core_dir();
  if (files_core_dir_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = files_core_dir_;
    files_core_dir_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CaffeGenData::set_allocated_files_core_dir(::std::string* files_core_dir) {
  if (files_core_dir_ != &::google::protobuf::internal::kEmptyString) {
    delete files_core_dir_;
  }
  if (files_core_dir) {
    set_has_files_core_dir();
    files_core_dir_ = files_core_dir;
  } else {
    clear_has_files_core_dir();
    files_core_dir_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string test_list_file_name = 8;
inline bool CaffeGenData::has_test_list_file_name() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void CaffeGenData::set_has_test_list_file_name() {
  _has_bits_[0] |= 0x00000080u;
}
inline void CaffeGenData::clear_has_test_list_file_name() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void CaffeGenData::clear_test_list_file_name() {
  if (test_list_file_name_ != &::google::protobuf::internal::kEmptyString) {
    test_list_file_name_->clear();
  }
  clear_has_test_list_file_name();
}
inline const ::std::string& CaffeGenData::test_list_file_name() const {
  return *test_list_file_name_;
}
inline void CaffeGenData::set_test_list_file_name(const ::std::string& value) {
  set_has_test_list_file_name();
  if (test_list_file_name_ == &::google::protobuf::internal::kEmptyString) {
    test_list_file_name_ = new ::std::string;
  }
  test_list_file_name_->assign(value);
}
inline void CaffeGenData::set_test_list_file_name(const char* value) {
  set_has_test_list_file_name();
  if (test_list_file_name_ == &::google::protobuf::internal::kEmptyString) {
    test_list_file_name_ = new ::std::string;
  }
  test_list_file_name_->assign(value);
}
inline void CaffeGenData::set_test_list_file_name(const char* value, size_t size) {
  set_has_test_list_file_name();
  if (test_list_file_name_ == &::google::protobuf::internal::kEmptyString) {
    test_list_file_name_ = new ::std::string;
  }
  test_list_file_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CaffeGenData::mutable_test_list_file_name() {
  set_has_test_list_file_name();
  if (test_list_file_name_ == &::google::protobuf::internal::kEmptyString) {
    test_list_file_name_ = new ::std::string;
  }
  return test_list_file_name_;
}
inline ::std::string* CaffeGenData::release_test_list_file_name() {
  clear_has_test_list_file_name();
  if (test_list_file_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = test_list_file_name_;
    test_list_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CaffeGenData::set_allocated_test_list_file_name(::std::string* test_list_file_name) {
  if (test_list_file_name_ != &::google::protobuf::internal::kEmptyString) {
    delete test_list_file_name_;
  }
  if (test_list_file_name) {
    set_has_test_list_file_name();
    test_list_file_name_ = test_list_file_name;
  } else {
    clear_has_test_list_file_name();
    test_list_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string train_list_file_name = 9;
inline bool CaffeGenData::has_train_list_file_name() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void CaffeGenData::set_has_train_list_file_name() {
  _has_bits_[0] |= 0x00000100u;
}
inline void CaffeGenData::clear_has_train_list_file_name() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void CaffeGenData::clear_train_list_file_name() {
  if (train_list_file_name_ != &::google::protobuf::internal::kEmptyString) {
    train_list_file_name_->clear();
  }
  clear_has_train_list_file_name();
}
inline const ::std::string& CaffeGenData::train_list_file_name() const {
  return *train_list_file_name_;
}
inline void CaffeGenData::set_train_list_file_name(const ::std::string& value) {
  set_has_train_list_file_name();
  if (train_list_file_name_ == &::google::protobuf::internal::kEmptyString) {
    train_list_file_name_ = new ::std::string;
  }
  train_list_file_name_->assign(value);
}
inline void CaffeGenData::set_train_list_file_name(const char* value) {
  set_has_train_list_file_name();
  if (train_list_file_name_ == &::google::protobuf::internal::kEmptyString) {
    train_list_file_name_ = new ::std::string;
  }
  train_list_file_name_->assign(value);
}
inline void CaffeGenData::set_train_list_file_name(const char* value, size_t size) {
  set_has_train_list_file_name();
  if (train_list_file_name_ == &::google::protobuf::internal::kEmptyString) {
    train_list_file_name_ = new ::std::string;
  }
  train_list_file_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CaffeGenData::mutable_train_list_file_name() {
  set_has_train_list_file_name();
  if (train_list_file_name_ == &::google::protobuf::internal::kEmptyString) {
    train_list_file_name_ = new ::std::string;
  }
  return train_list_file_name_;
}
inline ::std::string* CaffeGenData::release_train_list_file_name() {
  clear_has_train_list_file_name();
  if (train_list_file_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = train_list_file_name_;
    train_list_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CaffeGenData::set_allocated_train_list_file_name(::std::string* train_list_file_name) {
  if (train_list_file_name_ != &::google::protobuf::internal::kEmptyString) {
    delete train_list_file_name_;
  }
  if (train_list_file_name) {
    set_has_train_list_file_name();
    train_list_file_name_ = train_list_file_name;
  } else {
    clear_has_train_list_file_name();
    train_list_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required .CaffeGenData.NetEndType net_end_type = 10;
inline bool CaffeGenData::has_net_end_type() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void CaffeGenData::set_has_net_end_type() {
  _has_bits_[0] |= 0x00000200u;
}
inline void CaffeGenData::clear_has_net_end_type() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void CaffeGenData::clear_net_end_type() {
  net_end_type_ = 1;
  clear_has_net_end_type();
}
inline ::CaffeGenData_NetEndType CaffeGenData::net_end_type() const {
  return static_cast< ::CaffeGenData_NetEndType >(net_end_type_);
}
inline void CaffeGenData::set_net_end_type(::CaffeGenData_NetEndType value) {
  assert(::CaffeGenData_NetEndType_IsValid(value));
  set_has_net_end_type();
  net_end_type_ = value;
}

// required string proto_file_name = 11;
inline bool CaffeGenData::has_proto_file_name() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void CaffeGenData::set_has_proto_file_name() {
  _has_bits_[0] |= 0x00000400u;
}
inline void CaffeGenData::clear_has_proto_file_name() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void CaffeGenData::clear_proto_file_name() {
  if (proto_file_name_ != &::google::protobuf::internal::kEmptyString) {
    proto_file_name_->clear();
  }
  clear_has_proto_file_name();
}
inline const ::std::string& CaffeGenData::proto_file_name() const {
  return *proto_file_name_;
}
inline void CaffeGenData::set_proto_file_name(const ::std::string& value) {
  set_has_proto_file_name();
  if (proto_file_name_ == &::google::protobuf::internal::kEmptyString) {
    proto_file_name_ = new ::std::string;
  }
  proto_file_name_->assign(value);
}
inline void CaffeGenData::set_proto_file_name(const char* value) {
  set_has_proto_file_name();
  if (proto_file_name_ == &::google::protobuf::internal::kEmptyString) {
    proto_file_name_ = new ::std::string;
  }
  proto_file_name_->assign(value);
}
inline void CaffeGenData::set_proto_file_name(const char* value, size_t size) {
  set_has_proto_file_name();
  if (proto_file_name_ == &::google::protobuf::internal::kEmptyString) {
    proto_file_name_ = new ::std::string;
  }
  proto_file_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CaffeGenData::mutable_proto_file_name() {
  set_has_proto_file_name();
  if (proto_file_name_ == &::google::protobuf::internal::kEmptyString) {
    proto_file_name_ = new ::std::string;
  }
  return proto_file_name_;
}
inline ::std::string* CaffeGenData::release_proto_file_name() {
  clear_has_proto_file_name();
  if (proto_file_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = proto_file_name_;
    proto_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CaffeGenData::set_allocated_proto_file_name(::std::string* proto_file_name) {
  if (proto_file_name_ != &::google::protobuf::internal::kEmptyString) {
    delete proto_file_name_;
  }
  if (proto_file_name) {
    set_has_proto_file_name();
    proto_file_name_ = proto_file_name;
  } else {
    clear_has_proto_file_name();
    proto_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string model_file_name = 12;
inline bool CaffeGenData::has_model_file_name() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void CaffeGenData::set_has_model_file_name() {
  _has_bits_[0] |= 0x00000800u;
}
inline void CaffeGenData::clear_has_model_file_name() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void CaffeGenData::clear_model_file_name() {
  if (model_file_name_ != &::google::protobuf::internal::kEmptyString) {
    model_file_name_->clear();
  }
  clear_has_model_file_name();
}
inline const ::std::string& CaffeGenData::model_file_name() const {
  return *model_file_name_;
}
inline void CaffeGenData::set_model_file_name(const ::std::string& value) {
  set_has_model_file_name();
  if (model_file_name_ == &::google::protobuf::internal::kEmptyString) {
    model_file_name_ = new ::std::string;
  }
  model_file_name_->assign(value);
}
inline void CaffeGenData::set_model_file_name(const char* value) {
  set_has_model_file_name();
  if (model_file_name_ == &::google::protobuf::internal::kEmptyString) {
    model_file_name_ = new ::std::string;
  }
  model_file_name_->assign(value);
}
inline void CaffeGenData::set_model_file_name(const char* value, size_t size) {
  set_has_model_file_name();
  if (model_file_name_ == &::google::protobuf::internal::kEmptyString) {
    model_file_name_ = new ::std::string;
  }
  model_file_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CaffeGenData::mutable_model_file_name() {
  set_has_model_file_name();
  if (model_file_name_ == &::google::protobuf::internal::kEmptyString) {
    model_file_name_ = new ::std::string;
  }
  return model_file_name_;
}
inline ::std::string* CaffeGenData::release_model_file_name() {
  clear_has_model_file_name();
  if (model_file_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = model_file_name_;
    model_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CaffeGenData::set_allocated_model_file_name(::std::string* model_file_name) {
  if (model_file_name_ != &::google::protobuf::internal::kEmptyString) {
    delete model_file_name_;
  }
  if (model_file_name) {
    set_has_model_file_name();
    model_file_name_ = model_file_name;
  } else {
    clear_has_model_file_name();
    model_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string config_file_name = 13;
inline bool CaffeGenData::has_config_file_name() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void CaffeGenData::set_has_config_file_name() {
  _has_bits_[0] |= 0x00001000u;
}
inline void CaffeGenData::clear_has_config_file_name() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void CaffeGenData::clear_config_file_name() {
  if (config_file_name_ != &::google::protobuf::internal::kEmptyString) {
    config_file_name_->clear();
  }
  clear_has_config_file_name();
}
inline const ::std::string& CaffeGenData::config_file_name() const {
  return *config_file_name_;
}
inline void CaffeGenData::set_config_file_name(const ::std::string& value) {
  set_has_config_file_name();
  if (config_file_name_ == &::google::protobuf::internal::kEmptyString) {
    config_file_name_ = new ::std::string;
  }
  config_file_name_->assign(value);
}
inline void CaffeGenData::set_config_file_name(const char* value) {
  set_has_config_file_name();
  if (config_file_name_ == &::google::protobuf::internal::kEmptyString) {
    config_file_name_ = new ::std::string;
  }
  config_file_name_->assign(value);
}
inline void CaffeGenData::set_config_file_name(const char* value, size_t size) {
  set_has_config_file_name();
  if (config_file_name_ == &::google::protobuf::internal::kEmptyString) {
    config_file_name_ = new ::std::string;
  }
  config_file_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CaffeGenData::mutable_config_file_name() {
  set_has_config_file_name();
  if (config_file_name_ == &::google::protobuf::internal::kEmptyString) {
    config_file_name_ = new ::std::string;
  }
  return config_file_name_;
}
inline ::std::string* CaffeGenData::release_config_file_name() {
  clear_has_config_file_name();
  if (config_file_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = config_file_name_;
    config_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CaffeGenData::set_allocated_config_file_name(::std::string* config_file_name) {
  if (config_file_name_ != &::google::protobuf::internal::kEmptyString) {
    delete config_file_name_;
  }
  if (config_file_name) {
    set_has_config_file_name();
    config_file_name_ = config_file_name;
  } else {
    clear_has_config_file_name();
    config_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CaffeGenData_IterateType>() {
  return ::CaffeGenData_IterateType_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CaffeGenData_DataSrc>() {
  return ::CaffeGenData_DataSrc_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CaffeGenData_NetEndType>() {
  return ::CaffeGenData_NetEndType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GenData_2eproto__INCLUDED
